name: benchmark sanity check

on:
  push:
    branches:
      - doc-refine
    paths-ignore:
      - '**.md'
      - '**.png'

env:
  RUST_TOOLCHAIN: nightly
  TOOLCHAIN_PROFILE: minimal

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout-Sources
        uses: actions/checkout@v2
      - name: Install-Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: ${{ env.TOOLCHAIN_PROFILE }}
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          override: true
      - name: Build-Proxy
        run: |
          sudo apt-get install -y pkg-config
          cargo build --verbose
      - name: Cache
        uses: Swatinem/rust-cache@v1
      - name: Setup-Certs
        run: |
          cd /home/runner/work/monolake/examples/ && 
          ./gen_cert.sh &&
          cp certs/server.key certs/key.pem &&
          cp certs/server.crt certs/cert.pem
      - name: Run-Proxy
        uses: actions-rs/cargo@v1
        with:
          command: "run"
          args: "--package monolake -- -c benchmark/proxy/monolake/monolake.toml &"
      - name: Install-Run-Server
        run: |
          sudo apt-get update &&
          sudo apt-get install -y openssl nginx &&
          sudo cp ./benchmark/server/nginx-web.conf /etc/nginx/nginx.conf &&
          sudo cp -r ./benchmark/server/webroot/* /usr/share/nginx/html/ &&
          cd /home/runner/work/monolake &&
          cat examples/certs/server.key examples/certs/server.pkcs8 > ./combined.pem &&
          sudo mv ./combined.pem /etc/nginx/ &&
          sudo cp examples/certs/cert.pem /etc/nginx/ &&
          sudo systemctl enable nginx &&
          sudo systemctl start nginx &&
          cd /home/runner/work &&
          sleep 2
      - name: Checkout-Client
        uses: actions/checkout@v2
        with:
          repository: 'giltene/wrk2'
          path: 'wrk2'
      - name: Build-Client
        run: |
          sudo apt-get -y install gcc make git libssl-dev zlib1g-dev &&
          cd wrk2 &&
          make WITH_OPENSSL=/usr &&
          cd /home/runner/work &&
          sleep 2
      - name: Run-Client
        run: |
          curl -vvv http://localhost:8402 &&
          cd wrk2 &&
          ./wrk -d 1m -c 640 -t 64 -R 200000 --latency http://localhost:8402 &&
          sleep 2
